### ISSUE TITLE
[rookie] getRenderPanel() in humble

### ISSUE THREAD

**Issue by h3ngy1ng** [ros2/rviz#1260]
I have the below code snippets where I wish to init the ViewportMouseEvent before passing into void UpdateNodePosition::processMouseEvent(rviz_common::ViewportMouseEvent& event). 

**Question:** How do I getRenderPanel() in humble? I have tried several ways and I dont see such function in the repo. Thanks!
    
    
![Screenshot from 2024-08-20 12-13-28](https://github.com/user-attachments/assets/8ca15f4a-56a3-4b35-ab58-4ca97c791fbd)
![Screenshot from 2024-08-20 12-13-51](https://github.com/user-attachments/assets/e24bdfef-725d-4c1e-a62a-8b4b5193b95c)

**Comment by sloretz** [comment]
Hi @h3ngy1ng, What type of RViz plugin are you creating? Have you seen this guide? https://github.com/ros2/rviz/blob/rolling/docs/plugin_development.md . Please ask follow up questions on https://robotics.stackexchange.com/?tags=ros

If you're creating a Display plugin you can use [this->context_](https://github.com/ros2/rviz/blob/993797558264f556528c5824d4ec4c9196886339/rviz_common/include/rviz_common/display.hpp#L368)->[getViewManager()](https://github.com/ros2/rviz/blob/993797558264f556528c5824d4ec4c9196886339/rviz_common/include/rviz_common/display_context.hpp#L185)->[getRenderPanel()](https://github.com/ros2/rviz/blob/993797558264f556528c5824d4ec4c9196886339/rviz_common/include/rviz_common/view_manager.hpp#L131)

In the future, please post text instead of pictures or screenshots of text. It makes it easier for others with the same question to find this issue in the future.
