### ISSUE TITLE
ros2 run rviz2 rviz2

### ISSUE THREAD

**Issue by jeising** [ros2/rviz#162]
Currently in the deb package there is rviz2 available, but it is not start-able via ros2 run. To enable this would enhance the usability and user experience of rviz.

**Comment by wjwwood** [comment]
Yup, this is something we wanted to do before the release, but just didn't have time. Also since the binary is currently statically linked against `rviz_common`, it is pretty large, so I hesitated to duplicate it. I'm sure we could come up with another way to install the binary once and provide a redirection or script or something to run it the other way.
