### ISSUE TITLE
Error launching rviz in docker container

### ISSUE THREAD

**Issue by alsora** [ros2/rviz#347]
Hi,

I'm trying to use Rviz2 from within a Docker container.

I'm working on top of this Docker image

``FROM osrf/ros2:bouncy-desktop``

This is my run script 
````
#!/bin/bash

XSOCK=/tmp/.X11-unix

XAUTH=/tmp/.docker.xauth

touch $XAUTH

xauth nlist $DISPLAY | sed -e 's/^..../ffff/' | xauth -f $XAUTH nmerge -

docker run -it --rm \
  -e XAUTHORITY=${XAUTH} \
  -e DISPLAY=$DISPLAY \
  -e QT_GRAPHICSSYSTEM=native \
  -v $XSOCK:$XSOCK:rw \
  -v $XAUTH:$XAUTH:rw \
  ros2_docker \
  bash
````
Everything works fine, but then I needed to make the Docker container communicate with other machines on the host network.
I accomplished that by adding the following option to docker run
``  --net=host \``

This solves the connectivity issue, but has the side effect of making rviz not working anymore.
If I try to run rviz, I only get the following error.
``  ros2 run rviz2 rviz2``
> QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
dbus[1041]: The last reference on a connection was dropped without closing the connection. This is a bug in an application. See dbus_connection_unref() documentation for details.
Most likely, the application was supposed to call dbus_connection_close(), since this is a private connection.
  D-Bus not built with -rdynamic so unable to print a backtrace

Any idea about how to fix this? Thanks

**Comment by sloretz** [comment]
I am not sure if you have seen the [ROS support guidelines](http://wiki.ros.org/Support) but we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

The rational for asking all kind of questions in a single place is:
* There are many more people reading questions there, so your chances of getting an answer in a timely manner are much higher.
* In the future other users will search there for similar problems and can find your question.
* The issue tracker in this repo is used to track bugs, feature requests, etc. It looks like this question might not be such an action item.

I will close this ticket for now, but would be happy to reopen if this turns out to be a bug. If you have asked your question on answers.ros.org please add a link to the question to this ticket so that future readers can find it.
