### ISSUE TITLE
[rviz_rendering] implement and document replacement for media_export

### ISSUE THREAD

**Issue by wjwwood** [ros2/rviz#4]
In rviz in ROS 1, a package called `media_export` was used in combination with the `ROS_PACKAGE_PATH` via the `rospack` C++ API to allow other packages to include resources for Ogre to be used with their rviz plugins.

That code has been commented out in the ros2 port, but we need to find a suitable alternative for ROS 2. Again, this means using `ament_index` in a similar way as described in https://github.com/ros2/rviz/issues/3, but instead of using it to find one package you would use it to find packages which provide media for Ogre by looking at a different ament index resource, something like `rviz_ogre_media_exports` or similar. For details on ament index and how it could be used to do this, see resources linked to in https://github.com/ros2/rviz/issues/3.

**Comment by Martin-Idel** [comment]
Let's say we have a package `my_rviz_plugin` which wants to add a few meshes to rviz. In principle, this means we need to call `getResourceLocation(...)` from the `Ogre::ResourceGroupManager`.

The ament_index can provide us with paths to all packages providing a resource. To add our plugin to the list, we add a file `my_rviz_plugin` to `ament_index/resource_index/rviz_ogre_media_exports/`. The real resources would be located somewhere next to the ament_index directory.

It seems we now want to do the following: The `my_rviz_plugin` file contains a description containing all information of my_rviz_plugin necessary to call `getResourceLocation(...)` and adding the resources. Rviz can then load the resources at startup time when calling `RenderSystem::setupResources()`.

This would require that the format of the file `ament_index/resource_index/rviz_ogre_media_exports/my_rviz_plugin` needs to be specified. Simplest solution: The my_rviz_plugin-file contains the relative path to the resource folder. We just add every file we find (including subdirectories?) as a resource with location type "FileSystem" and resource group of e.g. the plugin's name. 

Is this what you have in mind?

**Comment by wjwwood** [comment]
@Martin-Idel sorry for not responding, but yes this is exactly what I was thinking. We can provide a cmake macro that packages (like your `my_rviz_plugin` package) can use to "register a directory" with ogre via rviz.

Reference to the old code, commented out:

-
 https://github.com/ros2/rviz/blob/ca8f42e43ba9eaa6e15434b47906d7580da1c14a/rviz_rendering/src/rviz_rendering/render_system.cpp#L333-L361

**Comment by Martin-Idel-SI** [comment]
@wjwwood No problem. 
I had a further look. Here is my suggestion for the interface we want to provide:

- The resource type is `rviz_ogre_media_exports`
- Since the macro `ament_index_register_resource` already exists, it is strictly speaking not necessary to provide a macro, you can just use it in conjunction with an `install` step. 

However, it might be nice to have a macro for convenience. My suggestion:
- Since OGRE uses shallow folders for faster search, we should too, hence I'm inclined to let the user add a list of folders.
- The interface could just be `register_rviz_ogre_media_exports(DIRECTORIES list of directories)`, where the directory paths are relative to CMAKE_CURRENT_SOURCE_DIR.
- The macro then registers the resource by adding a file to `ament_index` containing information to all specified folders containing media and copies the media folders to the correct location.

I'll start working on it.
