### ISSUE TITLE
Rviz crashes when using Marker with frame_locked = True

### ISSUE THREAD

**Issue by xbaelus** [ros2/rviz#479]
Hi,
Running on Ubuntu 18.04, ROS version dashing. When trying to use Marker with `frame_locked = True`, Rviz crashes with the following exception:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  can't compare times with different time sources
```
even though there's only one node and time is obtained in exactly the same way in all parts of my application. There's a simple script to reproduce the issue ([rviz_crash.py.txt](https://github.com/ros2/rviz/files/3866474/rviz_crash.py.txt)); the crash occurs as soon as `mesh_test` topic is added to visualization in Rviz. There's also a thread on [answers.ros.org](https://answers.ros.org/question/337851/ros2rviz2-cant-compare-times-with-different-time-sources/) about this.

**Comment by jacobperron** [comment]
I think the bug is this line:

https://github.com/ros2/rviz/blob/045227a9fc251ab9e5af763bddc1f203aff6feac/rviz_default_plugins/src/rviz_default_plugins/displays/marker/markers/marker_base.cpp#L108

We should ensure that the zero timestamp has the appropriate clock type so that the comparison doesn't fail. I'll open a PR with a fix shortly.
