### ISSUE TITLE
Mac OS X eloquent release links to outdated libassimp 

### ISSUE THREAD

**Issue by capaulson** [ros2/rviz#488]
Potentially related to #140. Current version in brew is 5.0.0. On launch of rviz from the installed release one gets the following error: 
```
dyld: Library not loaded: /usr/local/opt/assimp/lib/libassimp.4.dylib
  Referenced from: /Users/cpaulson/ros2_eloquent/ros2-osx/lib/rviz2/rviz2
  Reason: image not found
```

Surprisingly, a symbolic link is sufficient to get things running again:
```
ln -s libassimp.5.0.0.dylib libassimp.4.dylib
```

However, this should get properly fixed as users who follow the install instructions for the release will likely have this issue as well.

**Comment by wjwwood** [comment]
The problem is that our buildfarm uses assimp 4 to build, so our binaries use that. Unfortunately the rolling releases in homebrew make it pretty much impossible for us to keep working binaries. You'll have to wait until we upgrade our build machines and roll out new binaries.

Linking 5 to 4 is dangerous, though maybe will work for you...

I don't think this is the same issue as #140, but the result is based on what we did there (since we install assimp on the build machines, the binary is tied to the assimp version they use, not the latest or one we built and distribute with our binary).

@mjcarroll @nuclearsandwich FYI
