### ISSUE TITLE
rviz2 crashes randomly when running Navigation2

### ISSUE THREAD

**Issue by Kaiser-Wang** [ros2/rviz#787]
rviz2 crashes randomly when I'm running Navigation2. The error message is as follows:

` [rviz2-10] [ERROR] [1635234443.248890800] [rviz2]: InternalErrorException: Cannot create GL vertex buffer in GLHardwareVertexBuffer::GLHardwareVertexBuffer at /tmp/binarydeb/ros-foxy-rviz-ogre-vendor-8.2.2/obj-x86_64-linux-gnu/ogre-v1.12.1-prefix/src/ogre-v1.12.1/RenderSystems/GL/src/OgreGLHardwareVertexBuffer.cpp (line 46)`

`[rviz2-10] terminate called after throwing an instance of 'Ogre::InternalErrorException'`

`[rviz2-10]   what():  InternalErrorException: Cannot create GL vertex buffer in GLHardwareVertexBuffer::GLHardwareVertexBuffer at /tmp/binarydeb/ros-foxy-rviz-ogre-vendor-8.2.2/obj-x86_64-linux-gnu/ogre-v1.12.1-prefix/src/ogre-v1.12.1/RenderSystems/GL/src/OgreGLHardwareVertexBuffer.cpp (line 46)`

`[ERROR] [rviz2-10]: process has died [pid 8279, exit code -6, cmd '/opt/ros/foxy/lib/rviz2/rviz2 -d /opt/ros/foxy/share/nav2_bringup/rviz/nav2_default_view.rviz --ros-args -r __node:=rviz2 -r __node:=rviz2 --params-file /tmp/launch_params_ep5l7a6u'].`

I'm using Ubuntu 20.04 with ROS2 Foxy and OpenGL version string: 3.0 Mesa 20.0.8

**Comment by Phanx1** [comment]
I think I am having this same issue.
My setup is Ubuntu 20.04 on parallels on an M1 mac, but the same issue was seen on native Ubuntu 20.04, Running ROS2 foxy

I am running navigation2 on a differential drive robot. When I start using EKFs instead of differential drive for the transforms I get a similar crash message as shown bellow

`rviz2-8] [ERROR] [1635859560.961004556] [rviz2]: Vertex Program:rviz/glsl120/indexed_8bit_image.vert Fragment Program:rviz/glsl120/indexed_8bit_image.frag GLSL link result : 
[rviz2-8] active samplers with a different type refer to the same texture image unit
[rviz2-8] [INFO] [1635859560.988979895] [rviz2]: Trying to create a map of size 400 x 400 using 1 swatches
[rviz2-8] [ERROR] [1635859561.008206407] [rviz2]: InternalErrorException: Cannot create GL vertex buffer in GLHardwareVertexBuffer::GLHardwareVertexBuffer at /tmp/binarydeb/ros-foxy-rviz-ogre-vendor-8.2.5/obj-aarch64-linux-gnu/ogre-v1.12.1-prefix/src/ogre-v1.12.1/RenderSystems/GL/src/OgreGLHardwareVertexBuffer.cpp (line 46)
[rviz2-8] terminate called after throwing an instance of 'Ogre::InternalErrorException'
[rviz2-8]   what():  InternalErrorException: Cannot create GL vertex buffer in GLHardwareVertexBuffer::GLHardwareVertexBuffer at /tmp/binarydeb/ros-foxy-rviz-ogre-vendor-8.2.5/obj-aarch64-linux-gnu/ogre-v1.12.1-prefix/src/ogre-v1.12.1/RenderSystems/GL/src/OgreGLHardwareVertexBuffer.cpp (line 46)
[ERROR] [rviz2-8]: process has died [pid 18328, exit code -6, cmd '/opt/ros/foxy/lib/rviz2/rviz2 -d /home/parallels/kevin_bibs_use/install/fish_sim_bringup/share/fish_sim_bringup/rviz/fish_sim.rviz --ros-args -r __node:=rviz2 -r /tf:=tf -r /tf_static:=tf_static -r /goal_pose:=goal_pose -r /clicked_point:=clicked_point -r /initialpose:=initialpose'].
`

If I do not show local footprint I get the message bellow but navigation works. 
`
[rviz2-8] [INFO] [1635860479.152605268] [rviz2]: Trying to create a map of size 200 x 200 using 1 swatches
[rviz2-8] [ERROR] [1635860479.159972818] [rviz2]: Vertex Program:rviz/glsl120/indexed_8bit_image.vert Fragment Program:rviz/glsl120/indexed_8bit_image.frag GLSL link result : 
[rviz2-8] active samplers with a different type refer to the same texture image unit
[rviz2-8] [INFO] [1635860479.188407851] [rviz2]: Trying to create a map of size 400 x 400 using 1 swatches
`

Looking at /local_costmap/published_footprint vs /global_costmap/published_footprint the only difference is the frame_id odom for local, map for global which makes sense. But if i switch fixed frame in RViz from map to odom Rviz crashes with the top most error message.

**Comment by WonsokYoo** [comment]
@clalancette Is there any progress? Same phenomenon occured in my Foxy environment. Looks like crash problem has been resolved with 
https://github.com/ros2/geometry2/pull/490

but it was not applied to foxy branch.

**Comment by clalancette** [comment]
Unfortunately, we cannot backport those patches to Foxy as it changes API and ABI.  Someone will have to investigate and come up with another fix.

**Comment by clalancette** [comment]
Given that Foxy is now End-of-Life, I'm going to close this out.  If you are still having problems with this on newer ROS distributions (Humble or Iron), please feel free to open up a new issue.
