### ISSUE TITLE
ROS callbacks not processed if Qt dialog is open

### ISSUE THREAD

**Issue by jacobperron** [ros2/rviz#793]
To reproduce, visualize some data in Rviz (e.g. camera images, laser scans, etc) and then open the "add new display" dialog (Ctrl+N). You should notice that the displays stop updating. You should also notice that time stops updating in RViz.

This does not only affect displays, but also other ROS communication, for instance trying to set ROS parameters on RViz while a dialog is open causes the set parameter service call to block until the dialog is closed (or a timeout occurs).

I think the expected behavior should be that ROS callbacks are not blocked by Qt (at least ROS parameter updates should not be blocked).

I've noticed this bug is triggered by the "add new display" and "add a new tool" dialogs, but _not_ from the "about" dialog (accessed from the "help" menu, Alt+H then Alt+A).

**Comment by ivanpauno** [comment]
The cause of the issue is:

https://github.com/ros2/rviz/blob/0423b7bc144cab73022974c9a02b0c06dfed0fab/rviz_common/src/rviz_common/visualization_manager.cpp#L390
https://github.com/ros2/rviz/blob/0423b7bc144cab73022974c9a02b0c06dfed0fab/rviz_common/src/rviz_common/displays_panel.cpp#L134

I think that we don't need to stop updating when opening the dialog, but only after it's accepted.
I'm going to try that.
